### ISSUE TITLE
Add Remaining K8s Views

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/uds-runtime#32]
Implement views for the following:

```[tasklist]
### Cluster Ops
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/45
- [ ] https://github.com/defenseunicorns/uds-runtime/pull/42
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/47
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/48
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/49
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/50
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/46
- [x] Secrets (leave for Jeff)
- [x] Config Map (leave for jeff)
```

```[tasklist]
### Networks
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/41
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/51
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/52
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/53
```

```[tasklist]
### Storage
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/58
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/59
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/60
```

```[tasklist]
### Security
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/54
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/55
- [ ] https://github.com/defenseunicorns/uds-runtime/issues/56
- [ ] CVE report
- [ ] Security Overview/Dashboard
```

**Comment by decleaver** [comment]
@TristanHoladay looks like the linked issues get removed once they are merged/closed? But yeah, the services view has been completed.
